apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-db-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.10.2
        command:
        - mlflow
        - server
        - --backend-store-uri
        - sqlite:////mlflow-db/mlflow.db
        - --default-artifact-root
        - s3://mlflow-bucket/
        - --host
        - 0.0.0.0
        - --port
        - "5000"
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-service.mlops.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: mlflow-db-storage
          mountPath: /mlflow-db
      volumes:
      - name: mlflow-db-storage
        persistentVolumeClaim:
          claimName: mlflow-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlops
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: mlflow