apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mlops
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-mlops
  template:
    metadata:
      labels:
        app: fastapi-mlops
    spec:
      imagePullSecrets:
      - name: ocir-secret
      containers:
      - name: fastapi
        image: ap-kulai-2.ocir.io/axvb5wrms5km/mlops-serving-api:v1