apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mlops
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-mlops
  template:
    metadata:
      labels:
        app: fastapi-mlops
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000