apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mlops
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-mlops
  template:
    metadata:
      labels:
        app: fastapi-mlops
    spec:
      containers:
      - name: fastapi
        # CHANGE THIS LINE to match your registry full path and tag:
        image: axvb5wrms5km/mlops-serving-api:v1
        ports:
        - containerPort: 8000